### ISSUE TITLE
话题接口的一些已知bug

### ISSUE THREAD

**Issue by mzz2017** [Actooors/LabManagementSystem_service#10]
### 公共问题
- [ ] topic列表未按降序排列（最近发表的排最前）
- [x] comment列表未按降序排列（最近发表的排最前）
### 未登录的情况下
- [x] 添加comment、发布话题等情况下，未返回错误提示
- [x] 拉取comment列表时，应当全部是liked=false
### 已登录的情况下
- [x] 发布话题未判断标题、内容、类别是否为空，建议对内容的字数进行最大和最小值的限定
- [x] 点赞时，有时候已经like--了，但是liked没有消失，且点赞数不稳定，刷新后有时会还原（见topicid==2的郭孟然的comment）
- [x] 因为上述BUG，点赞数可能为负

**Comment by mzz2017** [comment]
- [ ] `/topic/addTopicComment`接口总是返回`给予的topicId错误`。测试数据：
```json
{"code": "FAILED", "message": "给予的topicId错误", "data": null}
```

**Comment by 0GGmr0** [comment]
问题解决
