### ISSUE TITLE
公告模板API

### ISSUE THREAD

**Issue by CoCoManYY** [Actooors/LabManagementSystem_service#7]
# 公告板块
主要发布各类大型活动的通知
有增加删除功能、（删除的功能自行判断time值，如果已经过期则自动从数据库删除）
#接口获取所有通知
## 描述
get请求，页面加载直接响应数据  
注意：type只有 ‘meeting’、‘outing’、‘competition’三种
## 相应数据样例
{
  "code":"SUCCESS",
  "message":null,
  "data":[
{
              type:'meeting',
              title:'关于XXX议会',
              content:"全体工作员在办公室开会，请大家安排好工作，准时参加会议。\n",
              author:"XXX 办公室",
              time:'X年XX月XX日下午14：00点',
              publishTime:"X年XX月XX日"
            },
            {
              type:'meeting',
              title:'关于XXX议会',
              content:"             今天下午14：00点全体工作员在办公室开会，请大家安排好工作，准时参加会议。\n",
              author:"XXX 办公室",
              time:'X年XX月XX日下午14：00点',
              publishTime:"X年XX月XX日"
            },
            {
              type:'meeting',
              title:'关于XXX议会',
              content:"             今天下午14：00点全体工作员在办公室开会，请大家安排好工作，准时参加会议。\n",
              author:"XXX 办公室",
              time:'X年XX月XX日下午14：00点',
              publishTime:"X年XX月XX日"
            },
            {
              type:'outing',
              title:'往深圳大学交流',
              content:"猜你喜欢\n" +
              "百度糯米\n" +
              "京东商城\n",
              author:"XXX 办公室",
              time:'X年XX月XX日下午14：00点',
              publishTime:"X年XX月XX日"
            },
            {
              type:'competition',
              title:'XXX大赛通知',
              content:"猜你喜欢\n" +
              "百度糯米\n" +
              "京东商城\n" +
              "1号店\n" +
              "苏宁易购\n",
              author:"XXX 办公室",
              time:'X年XX月XX日下午14：00点',
              publishTime:"X年XX月XX日"
            }
]
}

**Comment by CoCoManYY** [comment]
接口
发布公告

描述
POST请求，发布新的话题。请自行判断发布者（作者）以及发布时间等一起存入数据库。

请求参数样例
{
              type:'meeting',
              title:'关于XXX议会',
              content:"             今天下午14：00点全体工作员在办公室开会，请大家安排好工作，准时参加会议。\n",
              author:"XXX 办公室",
              time:"X年XX月XX日"
}
响应数据样
{
  "code": "SUCCESS",
  "message": null,
  "data":null
}

**Comment by 0GGmr0** [comment]
通知公告完成
返回所有的公告接口 /api/notice/allNotice
删除公告接口/api/notice/deleteNotice
增加公告接口/api/notice/addNotice
